version: "3.8"

services:
  puppeteer-worker:
    build:
      dockerfile: Dockerfile.puppeteer-worker
      context: .
    container_name: puppeteer-worker
    image: puppeteer-worker:latest
    platform: linux/amd64
    env_file:
      - env-prod/.env
      - env-prod/.puppeteer-worker.env
    ports:
      - "3001:3000"

  rest-server:
    build:
      context: .
      dockerfile: Dockerfile.rest-server
    image: rest-server:latest
    container_name: rest-server
    platform: linux/amd64
    env_file:
      - env-prod/.env
      - env-prod/.rest-server.env
    ports:
      - "3000:3000"
