# Use the official Node.js runtime as the base image
FROM node:22-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install Node.js dependencies
RUN npm install --omit=dev

# Copy the rest of the application code
COPY . .

# Verify google-auth-library is installed
RUN npm list google-auth-library

# Command to run the application
CMD ["npm", "run", "start:rest-server"]
