const GCLOUD_PROJECT_NR = process.env.GCLOUD_PROJECT_NUMBER;
const DEFAULT_LOCATION = process.env.DEFAULT_LOCATION;
const PUPPETEER_WORKER_SERVICE_NAME = process.env.PUPPETEER_WORKER_SERVICE_NAME;
const TARGET_AUDIENCE = `https://${PUPPETEER_WORKER_SERVICE_NAME}-${GCLOUD_PROJECT_NR}.${DEFAULT_LOCATION}.run.app/`;
const PUPPETEER_WORKER_URL = process.env.PUPPETEER_WORKER_URL;
const PORT = process.env.PORT;

export {
  TARGET_AUDIENCE,
  PUPPETEER_WORKER_SERVICE_NAME,
  PUPPETEER_WORKER_URL,
  PORT,
};
